<center><h1>Dailydeals</h1></center>
<?php 
date_default_timezone_set('Asia/Kolkata');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaPath=$objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);     
?> 
<?php
use Magento\Framework\App\Action\Action;
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$imageBlock = $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="c-product-container">
        <?php $iterator = 1; ?>
        <ol class="c-main-ol">
          <div class="owl-carousel owl-theme">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
              <?php if(1==1){?>
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-lg-12 c-main-li">
                <li class="item">
                <div class="c-inner-container">
                    <a href="<?php echo $_product->getProductUrl() ?>" tabindex="-1">
                  
                            <span >
                                <?php
                                $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_product, 'product_page_image_large')
                                        ->keepAspectRatio(TRUE)
                                        ->keepFrame(FALSE)
                                        ->resize(270, 371)
                                        ->getUrl();
                                ?>
                                <img  src="<?php echo $imageUrl; ?>" class="c-p-image"/>

                            </span>
                    </a>
                    <div class="test">
                    <div class="row c-after-image">
                        <div class="col-sm-12 col-md-8 c-p-name">
                        <div><?php echo $block->getProductDetailsHtml($_product); ?></div>
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>

                        <strong>
                            <a
                               href="<?php echo $_product->getProductUrl() ?>">
                                   <?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                    </div>
                    <div class="col-sm-12 col-md-4 c-p-price">
                         <?php echo $block->getProductPrice($_product) ?>
                    </div>
                </div>
                       <div class="row c-after-price">
                        <div style="width:25%" class="c-whishlist">
                          <center>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><i class="fa fa-heart"></i></span>
                                        </a>
                                    <?php endif; ?>
                                  </center>
                        </div>
                          <div style="width:50%" class="c-addtocart">

                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <center>
                                        <form data-role="tocart-form" action="<?php echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary" >
                                                <span><?php echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                        </center>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>

                                <div data-role="add-to-links" style="width:25%" class="c-compare">
                                  <center>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <span class="glyphicon">&#xe018;</span>
                                    </a>
                                  </center>
                                </div>
                            </div>
                                <div class="row">
                                    <div class="col-sm-12 col-md-12 c-p-review">
                                        <center>
                           <?php echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                       </center>
                             </div>
                         </div>
                                
                       </div> 
                    </div>
                </li>
            
        </div>
                <?php }?>
            <?php endforeach; ?>
          </div>
        </ol>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
            }
            }
        </script>
    <?php endif; ?>
<?php endif;?>
<script>
    require(['jquery', 'jquery/ui','c-owl-crousel'], function($){ 
    $( document ).ready(function() {
      var owl = $('.owl-carousel');
      owl.owlCarousel({
        loop: true,
        autoplay:true,
        nav:true,
        margin:0,
        responsive: {
          0:{
            items:1
          },
          300: {
            items: 2
          },
          600: {
            items: 2
          },
          1000: {
            items: 3
          },
          1300: {
            items:4
          }
        }
      })
      });
  });
    </script>



























